version: "3.8"

services:
  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    ports:
      - 81:80
    networks:
      - app-network
    volumes:
      - ./html:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: postgres
    container_name: db
    ports:
      - "54320:5432"
    env_file:
      - ./html/.env
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  app:
    container_name: app
    build:
      dockerfile: docker/php/phpfpm.Dockerfile
      context: .
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./html:/var/www

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    networks:
      - app-network
    ports:
      - '1080:1080'
      - '1025:1025'

  node:
    image: node:15-alpine
    container_name: node
    working_dir: /var/www
    volumes:
      - ./html:/var/www
      - /var/www/node_modules
    command: sh /var/www/node_start.sh
    ports:
      - 5173:5173
      - 5174:5174
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data: